version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker-php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443
    networks:
      - app

  mysql:
    image: wangxian/alpine-mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/mydata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: platform
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    networks:
      - app

#  redis:
#    image: redis:alpine
#    container_name: redis
#    restart: unless-stopped
#    environment:
#      SERVICE_NAME: redis
#    ports:
#      - 6379:6379
#    networks:
#      - app

networks:
  app:
    driver: bridge
