version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:alpine
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443

  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: platform
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
