version: '3'

networks:
  xhanzi:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/log:/var/log/nginx
    depends_on:
      - php
    networks:
      - xhanzi

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./sqlite3:/var/www/sqlite3
      - ./src:/var/www/html
      - ./logs:/var/www/html/storage/logs
    ports:
      - 9000:9000
    networks:
      - xhanzi
