version: '2'

services:
  app:
    build: .
    image: online
    restart: always
    container_name: online
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../xhanzi_data:/xhanzi/data:rw,delegated
