version: '3'

services:
  app:
    build: .
    image: xhanzi/online
    container_name: online
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - xhanzi

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html
      - ../xhanzi_data/database.sqlite3:/var/www/html/database/database.sqlite3
      - ../xhanzi_data/conf.d:/etc/nginx/conf.d
      - ../xhanzi_data/ssl:/etc/nginx/ssl
      - ../xhanzi_data/log:/var/log/nginx
    networks:
      - xhanzi

networks:
  xhanzi:
    driver: bridge
